#!/usr/bin/env python
import sys
if len(sys.argv) != 4:
    sys.stderr.write('Arguments are %s chunk-length offset output-len\n' 
                            % sys.argv[0])
    exit(-1)
l=int(sys.argv[1])
n=int(sys.argv[2])
N=int(sys.argv[3])
while True:
    chunk = sys.stdin.read(l)
    if len(chunk) < (n+N):
        break
    sys.stdout.write(chunk[n:n+N])
    if len(chunk) < l:
        break
exit(0)
